export default {
	nodes: [
		{
			shape: 'state',
			type: 'node',
			size: '170*34',
			x: -544.25,
			y: -643.8125,
			id: 'aa7ecf5c',
			index: 0,
			initial: true,
			label: 'red',
			onEntry: [],
			onExit: [],
		},
		{
			shape: 'state',
			type: 'node',
			size: '170*34',
			x: -766.25,
			y: -451.8125,
			id: 'cbf54fad',
			index: 1,
			initial: false,
			label: 'green',
			onEntry: [],
			onExit: [],
		},
		{
			shape: 'state',
			type: 'node',
			size: '170*34',
			x: -352.25,
			y: -452.3125,
			id: '8f5df612',
			index: 2,
			initial: false,
			label: 'yellow',
			onEntry: [],
			onExit: [],
		},
	],
	edges: [
		{
			source: '8f5df612',
			sourceAnchor: 3,
			target: 'aa7ecf5c',
			targetAnchor: 12,
			id: 'adc2f402',
			index: 3,
			label: 'timer',
		},
		{
			source: 'aa7ecf5c',
			sourceAnchor: 15,
			target: 'cbf54fad',
			targetAnchor: 2,
			id: 'ccecf940',
			index: 4,
			label: 'timer',
		},
		{
			source: 'cbf54fad',
			sourceAnchor: 13,
			target: '8f5df612',
			targetAnchor: 14,
			id: 'ecc663f4',
			index: 5,
			label: 'timer',
		},
	],
}
